### PR TITLE
Feature/support twitter login

### PR DESCRIPTION
**Pull request by incrediblink**
Should merge after #42 .

### CODE REVIEW

**Comment by theJian** [comment]
Looks like a duplicate of #38 . Do we still need this one to be merged?

**Comment by incrediblink** [comment]
@theJian This branch is based on `feature/url-scheme`. Maybe we should merge this to `feature/url-scheme` first, and then we can merge `feature/url-scheme` into `master` branch.

**Comment by theJian** [comment]
@incrediblink Sure.
btw have you successfully produced a working demo of notification? If not I'll try it again tonight. Connection issue seems to be solved by setting up a different proxy port to me.

**Comment by incrediblink** [comment]
@theJian I've successfully made a local notification on the current branch. I haven't tried the remote notification yet tho.

**Pull request merged**
